import { Download } from "lucide-react";
import type { RecentExportItem } from "../types/reports";

interface Props {
  exportsList: RecentExportItem[];
}

export function RecentExportsTable({ exportsList }: Props) {
  return (
    <div className="rounded-xl border border-border/80 bg-card p-6 shadow-sm space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <h2 className="text-sm font-semibold text-foreground">Recent Exports</h2>
          <span className="rounded-full bg-background border border-border px-2.5 py-0.5 text-[10px] font-semibold text-muted-foreground">LAST 30 DAYS</span>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-border/60 text-[10px] font-bold tracking-wider text-muted-foreground">
              <th className="py-3 px-4">FILENAME / REPORT</th>
              <th className="py-3 px-4">MODULES</th>
              <th className="py-3 px-4">FORMAT</th>
              <th className="py-3 px-4">GENERATED BY</th>
              <th className="py-3 px-4">DATE</th>
              <th className="py-3 px-4 text-right">ACTION</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border/40 text-xs">
            {exportsList.map((item) => (
              <tr key={item.id} className="hover:bg-background/40 transition-colors">
                <td className="py-4 px-4">
                  <div className="font-bold text-foreground">{item.filename}</div>
                  <div className="text-[10px] text-muted-foreground mt-0.5">{item.filesize}</div>
                </td>
                <td className="py-4 px-4">
                  <div className="flex flex-wrap gap-1.5">
                    {item.modules.map((mod, idx) => (
                      <span key={idx} className="rounded bg-background border border-border px-2 py-0.5 text-[9px] font-bold text-muted-foreground">
                        {mod}
                      </span>
                    ))}
                  </div>
                </td>
                <td className="py-4 px-4 font-medium text-foreground">{item.format}</td>
                <td className="py-4 px-4 text-muted-foreground whitespace-pre-line">{item.generatedBy}</td>
                <td className="py-4 px-4 text-muted-foreground whitespace-pre-line">{item.date}</td>
                <td className="py-4 px-4 text-right">
                  <button 
                    type="button" 
                    className="rounded-md p-2 text-muted-foreground hover:bg-primary/10 hover:text-primary transition-colors inline-flex items-center justify-center"
                    aria-label={`Download ${item.filename}`}
                  >
                    <Download className="h-4 w-4" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="pt-2 text-center border-t border-border/40">
        <button type="button" className="text-[11px] font-bold text-muted-foreground hover:text-foreground tracking-wider transition-colors">
          SHOW MORE RECENT ACTIVITY
        </button>
      </div>
    </div>
  );
}